### ISSUE TITLE
Not able to build Android Project, hitting Task :app:configureCMakeDebug[arm64-v8a]

### ISSUE THREAD

**Issue by apsky911** [lugg/react-native-config#843]
> Task :app:configureCMakeDebug[arm64-v8a] FAILED
C/C++: CMake Error at /project/node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:97 (target_link_libraries):
C/C++:   Cannot specify link libraries for target "react_codegen_RNCConfigModule"
C/C++:   which is not built by this project.
C/C++: Call Stack (most recent call first):
C/C++:   CMakeLists.txt:31 (include)

React Native version: 0.81.0
React Native Config version: ^1.5.7

Step to Reproduce:
#1 npx @react-native-community/cli init myApp
#2 yarn add react-native-config
#3 Additional configure on react-native-config
#4 cd android && ./gradlew build
#5 Build failed due to CMakelist

**Comment by maximizing** [comment]
+1

**Comment by rahulrajsbkk** [comment]
diff --git a/android/build/generated/source/codegen/jni/CMakeLists.txt b/android/build/generated/source/codegen/jni/CMakeLists.txt
new file mode 100644
index 0000000000000000000000000000000000000000..aea07d27016af43c49fac0d9c620915886817702
--- /dev/null
+++ b/android/build/generated/source/codegen/jni/CMakeLists.txt
@@ -0,0 +1,13 @@
+# Minimal stub CMakeLists for missing codegen outputs.
+# This defines the react_codegen_RNCConfigModule target so native builds
+# that expect generated code can link against a placeholder library.
+cmake_minimum_required(VERSION 3.4.1)
+
+# Create a small static library with a trivial source file so CMake has a target to link.
+add_library(react_codegen_RNCConfigModule STATIC "${CMAKE_CURRENT_SOURCE_DIR}/empty.cpp")
+
+# Expose the current source dir (if other CMake code expects include dirs)
+target_include_directories(react_codegen_RNCConfigModule PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
+
+# Prevent warnings when linked against: set an empty interface
+target_compile_definitions(react_codegen_RNCConfigModule INTERFACE "REACT_NATIVE_CONFIG_STUB")
\ No newline at end of file
diff --git a/android/build/generated/source/codegen/jni/empty.cpp b/android/build/generated/source/codegen/jni/empty.cpp
new file mode 100644
index 0000000000000000000000000000000000000000..7d3435dc85d9409dda5eac5721aee1fc0451ff8a
--- /dev/null
+++ b/android/build/generated/source/codegen/jni/empty.cpp
@@ -0,0 +1,2 @@
+// Auto-generated stub file to satisfy CMake when real codegen output is not present.
+extern "C" void __react_native_config_codegen_stub() {}
\ No newline at end of file
diff --git a/package.json b/package.json
index 3e4524ed6a59be13a6e3153d7f85c2ff23e8d5f4..93eb922a5629c076c9970a3c746c7cc814f7876d 100644
--- a/package.json
+++ b/package.json
@@ -54,19 +54,5 @@
     "react-native-windows": {
       "optional": true
     }
-  },
-  "codegenConfig": {
-    "name": "RNCConfigModule",
-    "type": "modules",
-    "jsSrcsDir": "./src",
-    "android": {
-      "javaPackageName": "com.luggit.reactnativeconfig"
-    },
-    "ios": {
-      "prefix": "RNC"
-    },
-    "windows": {
-      "cppNamespace": "RNCConfig"
-    }
   }
 }


This worked for me

**Comment by esneidermanzano** [comment]
I'm getting exactly the same issue after upgrading RN to 0.81, and latest android studio Narwhal 

Additional log error:
```
CMake Error at C:/RNU/cm/android/app/build/generated/autolinking/src/main/jni/Android-autolinking.cmake:23 (add_subdirectory):
add_subdirectory given source
"C:/RNU/cm/node_modules/react-native-config/android/build/generated/source/codegen/jni/"
which is not an existing directory.
Call Stack (most recent call first):
C:/RNU/cm/node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:94 (include)
CMakeLists.txt:31 (include)
```

**Comment by edritech93** [comment]
same for me

**Comment by Devbiswasnegi** [comment]
> try newArchEnabled=false in android/gradle.properties

What’s the purpose of the new React Native architecture if newArchEnabled = false?

**Comment by hemantasapkota** [comment]
+1 in `1.5.7`. Works if you downgrade to `1.5.6`.

**Comment by nazacity** [comment]
+1

**Comment by cl3i550n** [comment]
### Workaround: Disable autolinking for `react-native-config` and link manually

If you want to avoid editing `node_modules`, you can disable autolinking for `react-native-config` and add it manually in your Gradle setup.

**1. Add `react-native.config.js` at the root of your project:**
```js
module.exports = {
  dependencies: {
    'react-native-config': { platforms: { android: null } },
  },
};
```

**2. Edit s`ettings.gradle`:**
```js
include ':react-native-config'
project(':react-native-config').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-config/android')
```

**3. Edit `app/build.gradle`:**
```js
dependencies {
    implementation project(':react-native-config')
}
```

This way, React Native won’t try to run codegen/autolinking for react-native-config (which causes the CMake error), and the module will still be available in your Android build.

**Comment by cl3i550n** [comment]
> +1
> 
> RN :  0.80.0
> ndk: 27.1.12297006
> Cmake : 3.22.1
>  
> 1.5.8 (not working)
> 1.5.7 (not working)
> 1.5.6 (not working)
> 

Try my last message steps

**Comment by 01Boris** [comment]
+1

**Comment by luancurti** [comment]
fixed on `v1.5.9`

**Comment by nazacity** [comment]
i tried 1.5.9 still same error
work on 1.5.6

**Comment by RN-Akash** [comment]
@luancurti 
i tried 1.5.9 still same error

Please check Repo : https://github.com/RN-Akash/YTest_v9.git

Steps I followed:

1. Installed the package:                     npm i react-native-config
2. Navigated to the Android folder:   cd android
3.  ./gradlew clean → worked fine
4.  ./gradlew build → failed with an error

**Comment by ThalKod** [comment]
Still not working on 1.5.9, had to downgrade to 1.5.6 to make it work.
